name: marketnest
description: "A complete multi-vendor marketplace application inspired by Amazon's UI, powered by PrestaShop backend through a custom PHP proxy."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.0.0
  dio: ^5.0.0
  shared_preferences: ^2.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_grid_view: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/